apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
    createdAt: "2026-05-20T08:10:47Z"
    features.operators.openshift.io/disconnected: "true"
    features.operators.openshift.io/fips-compliant: "false"
    features.operators.openshift.io/proxy-aware: "false"
    features.operators.openshift.io/tls-profiles: "false"
    features.operators.openshift.io/token-auth-aws: "false"
    features.operators.openshift.io/token-auth-azure: "false"
    features.operators.openshift.io/token-auth-gcp: "false"
    operators.openshift.io/valid-subscription: '["OpenShift Container Platform", "OpenShift
      Platform Plus"]'
    operators.operatorframework.io/builder: operator-sdk-v1.42.2
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v4
  name: agent-sandbox-operator.v0.0.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - kind: SandboxClaim
      name: sandboxclaims.extensions.agents.x-k8s.io
      version: v1alpha1
    - kind: Sandbox
      name: sandboxes.agents.x-k8s.io
      version: v1alpha1
    - kind: SandboxTemplate
      name: sandboxtemplates.extensions.agents.x-k8s.io
      version: v1alpha1
    - kind: SandboxWarmPool
      name: sandboxwarmpools.extensions.agents.x-k8s.io
      version: v1alpha1
  description: Agent-sandbox enables easy management of isolated, stateful, singleton
    workloads, ideal for use cases like AI agent runtimes.
  displayName: Agent Sandbox Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - persistentvolumeclaims
          - pods
          - services
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - agents.x-k8s.io
          resources:
          - sandboxes
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - agents.x-k8s.io
          resources:
          - sandboxes/finalizers
          - sandboxes/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - coordination.k8s.io
          resources:
          - leases
          verbs:
          - create
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - events.k8s.io
          resources:
          - events
          verbs:
          - create
          - patch
        - apiGroups:
          - ""
          resources:
          - pods
          verbs:
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - ""
          - events.k8s.io
          resources:
          - events
          verbs:
          - create
          - patch
          - update
        - apiGroups:
          - agents.x-k8s.io
          resources:
          - sandboxes
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - coordination.k8s.io
          resources:
          - leases
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - extensions.agents.x-k8s.io
          resources:
          - sandboxclaims
          - sandboxtemplates
          - sandboxwarmpools
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - extensions.agents.x-k8s.io
          resources:
          - sandboxclaims/finalizers
          - sandboxclaims/status
          - sandboxtemplates/finalizers
          - sandboxtemplates/status
          - sandboxwarmpools/finalizers
          - sandboxwarmpools/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - networking.k8s.io
          resources:
          - networkpolicies
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        serviceAccountName: agent-sandbox-controller
      deployments:
      - label:
          app: agent-sandbox-controller
        name: agent-sandbox-controller
        spec:
          replicas: 1
          selector:
            matchLabels:
              app: agent-sandbox-controller
          strategy: {}
          template:
            metadata:
              labels:
                app: agent-sandbox-controller
            spec:
              containers:
              - args:
                - --leader-elect=true
                - --extensions
                image: registry.redhat.io/agent-sandbox/agent-sandbox-rhel9-operator@sha256:95c1ef44d6016b91ae6cc86bd6af1775dc15b3a66ddec652895f50821597530a
                name: agent-sandbox-controller
                ports:
                - containerPort: 8080
                  name: metrics
                  protocol: TCP
                - containerPort: 8081
                  name: healthz
                  protocol: TCP
                resources: {}
              serviceAccountName: agent-sandbox-controller
    strategy: deployment
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - agent
  - sandbox
  - kubernetes
  links:
  - name: Agent Sandbox Operator
    url: https://agent-sandbox-operator.domain
  maintainers:
  - email: eesposit@redhat.com
    name: Emanuele Giuseppe Esposito
  maturity: alpha
  provider:
    name: kubernetes-sigs
    url: https://agent-sandbox.sigs.k8s.io/
  version: 0.0.1
