apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: sandbox-router
  name: sandbox-router-svc
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: sandbox-router
  type: ClusterIP
status:
  loadBalancer: {}
